# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'quebn/rosepine-tmux'
set -g @rose_pine_variant 'moon'

# Config
set -g base-index 1
set -g pane-base-index 1
set -g mouse on

# Replace index from 0 to 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -sa terminal-overrides ",xterm*:Tc"

# Remaps
unbind C-b
set -g prefix `
bind ` send-prefix

run '~/.tmux/plugins/tpm/tpm'
